= CalConnect/ISO 34300: Date and time -- Codes for calendar systems

This work item belongs to CalConnect TC DATETIME and ISO/TC 154/WG 5.

image:https://gitlab.com/calconnect/tc-datetime/csd-calendar-sytems/badges/master/pipeline.svg["Build Status (master)", link="https://gitlab.com/calconnect/tc-datetime/csd-calendar-sytems/pipelines"]

This document is available in its rendered forms here:

* https://calconnect.github.io/csd-calendar-systems/[CC/ISO 34300: Date and time -- Codes for calendar systems]


== Fetching the document

[source,sh]
----
git clone https://gitlab.com/calconnect/tc-datetime/csd-calendar-sytems
----


== Installing Build Tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=metanorma/metanorma
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make
----

The following outputs will be built:

* Document index at `documents.html`
* ISO 34300 at `documents/iso-34300.html`
* CC 34300 at `documents/iso-34300.html`
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make
open documents/iso-34300.html
open documents/cc-34300.html
----
