
[[codes]]
== Codes and identifiers

=== Principles for inclusion in the list of calendar systems

==== List

The list of calendar systems in this document includes known
calendar systems from bibliographic sources.

==== Source of names

Names and description of calendar systems are
obtained from authoritative sources.

==== Current status of names

Calendar systems listed in this document are intended to reflect the current situation, at the time of issue of the latest update of this document.



=== Principles for allocation of code elements

==== Relationship with names

Calendar systems have codes in the following format:

[source]
----
[system-code]
----

[example]
`gre` for the Gregorian calendar, whose specification is
provided in <<ISO8601-1>>.


==== Construction of the alphabetic code

The following rules are to be adhered to for the assignment of the alphabetic code:

* The alphabetic code uses combinations, in upper case, of 3 fixed letters of the 26-character Latin alphabet, allowing for close to stem:[3^26] combinations.

* Codes shall encourage descriptive and distinguishable alphabetic names.


==== User assigned code elements

If users need code elements to represent calendar systems not included in the calendar code registry, the code prefix of `zz` can be used.

The code length for the calendar system identifier must be 3 letters.

Such calendar system identifiers are in the following format:

[source]
----
zz[calendar-system-identifier]
----

////
[example]
`xx-unece-cet` is an example of a user-assigned private code for a calendar code published by the UN/ECE.
////

NOTE: Users are advised that the above series of codes are not universals, those code elements are not compatible between different entities.


=== List of calendar system and their code elements

The list of items composing the content of the country code is initially defined in <<annex-system-codes>>.
Additional and new entries will be listed by the ISO 34300/AG.

Data attributes provided in the list is defined in <<codes>>.

