
[[codes]]
== Codes and identifiers

[[scsa-requirements]]
=== Requirements

==== General

A calendar system is eligible for assignment of an entry based on its usage of date identification and the need for international interchange.

Usage of a calendar system is determined by at least one of the following conditions, by presentation of evidence:

* The system has been approved for official use at some level of government (current, historic, or will be in the near future);

* The system has been used to identify with dates, such as in bibliographic information (current, historic, or will be in the near future).

Justification should be given to indicate that international interchange is necessary.

A similar set of requirements apply to the registration of calendar eras. A calendar era entry must be associated
with at least one calendar system entry.


////
==== Current systems

A calendar system may be marked with usage
////


=== Principles for allocation of code elements

==== Relationship with names

Calendar systems have codes in the following format:

[source]
----
[system-code]
----

[example]
`gregorian` or `gre` for the Gregorian calendar, whose specification is
provided in <<ISO8601-1>>.


==== Construction of the alphabetic code

The following rules are to be adhered to for the assignment of the alphabetic code:

* The alphabetic code uses combinations, in lower case, of between 3 and 20 fixed letters of the 26-character Latin alphabet.

* Codes shall encourage descriptive and distinguishable alphabetic names.

An additional short alias for the alphabetic code composed of 3 fixed letters of the 26-character Latin alphabet is allowed.

//, allowing for close to stem:[3^26] combinations.


==== User assigned code elements

If users need code elements to represent calendar systems not included in the calendar code registry, the code prefix of `zz` can be used.

The code length for the calendar system identifier must be 3 letters.

Such calendar system identifiers are in the following format:

[source]
----
zz[calendar-system-identifier]
----

////
[example]
`xx-unece-cet` is an example of a user-assigned private code for a calendar code published by the UN/ECE.
////

NOTE: Users are advised that the above series of codes are not universals, those code elements are not compatible between different entities.


=== List of calendar system and their code elements

The list of items composing the content of the country code is initially
compiled in a separate dataset outside of this document.
Additional and new entries will be listed by the ISO {docnumber}/AG.

Data attributes provided in the list is defined in <<codes>>.

