
[[AnnexA]]
[appendix]
== Registration

=== Registration authority (ISO {docnumber}/RA)

A registration authority (ISO {docnumber}/RA) has been appointed to operate under guidelines provided in this Annex. It has been entrusted with the following functions:

. to add and eliminate calendar system and calendar era codes, in accordance with the rules in this document;

. to advise users and ISO member bodies regarding application of the codes;

. to update and disseminate list of calendar system and calendar era codes;

. to maintain a reference list of calendar system and calendar era codes;

. to publish changes made to such information;

. to administer the reservation of codes related to the list of calendar system and calendar era codes.

Changes to the content of the list of codes becomes effective immediately upon publication.

The criteria provided in <<registration-adding-tzauth>> to <<registration-modify-tz>> shall be observed by the ISO {docnumber}/AG for changes to the list of code elements, and for reservations of code elements.


=== Advisory group (ISO {docnumber}/AG)

An advisory group (ISO {docnumber}/AG) has been appointed to ensure the operations of the registration authority (ISO {docnumber}/RA) are in accordance with guidelines provided in this Annex.


[[registration-adding-tzauth]]
=== Addition to the list of calendar system and calendar era codes

Additions to the list of calendar system and calendar era codes shall be made on the basis of information from upon the request of a member of ISO {docnumber}/AG.

The ISO {docnumber}/AG will decide upon the addition, on the basis of the justification given for the actual requirements for interchange or encoding. Code elements will be allocated accordingly.

Basic eligibility for a calendar system to be assigned a calendar system code is one of:

* The system has been approved for official use at some level of government (current or historic);

* The system has had significant use in history;

* The system is in current use.


A calendar era to be assigned a calendar era code has to be associated
with at least one eligible calendar system.
Since a calendar system requires at least one calendar era, the application
and assignment of calendar system and calendar era codes can be performed
at once.


////
Additions to the official and international time scale authorities require additional criteria:

* An official time scale authority must be endorsed by a body receiving direct authority by a member of the United Nations.
* An international time scale authority must be endorsed by an international standardization body in liaison with the ISO {docnumber}/AG.
////


[[registration-removing-tzauth]]
=== Deletion from the list of calendar system and calendar era codes

Deletion from the list of calendar system and calendar era codes shall be made upon the request of a member of ISO {docnumber}/AG.

The ISO {docnumber}/AG will decide upon the deletion, on the basis of the information received. The corresponding code element is reserved.

////
The part 3 of ISO {docnumber} standard provides the list of country names deleted from the part 1 of ISO {docnumber} since its first edition in 1974. The traceability of country code elements and their status are also provided.
////


[[registration-deleting-tz]]
=== Deletion of elements from the list of calendar system and calendar era codes

Deletion from the list of calendar system and calendar era codes shall be made only by the ISO {docnumber}/AG or upon a request to it.

The ISO {docnumber}/AG will decide upon the deletion, on the basis of the information received. The corresponding code element is reserved.


[[registration-modify-tz]]
=== Alterations to elements on list of calendar system and calendar era codes

Alterations to a registered element shall be made only by the ISO {docnumber}/AG or upon a request to it.

A significant change of name may require the ISO {docnumber}/AG to change the alpha code element concerned. The ISO {docnumber}/AG, however, shall endeavor to maintain stability in the list of code elements.


////
=== Reservation of country code elements

==== Introduction

Some code elements are reserved
—	for a limited period when their reservation is the result of the deletion (6.3) or the alteration (6.4) of a country name,
—	for an indeterminate period when the reservation is the result of the application of international law (6.5.3) or of exceptional requests (6.5.4).

==== Period of non-allocation

Country code elements that the ISO {docnumber}/AG has altered or deleted should not be reallocated during a period of at least fifty years after the change. The exact period is determined in each case on the basis of the extent to which the former code element was used.

==== Period of non-use

Certain country code elements existing at the time of the first publication of the ISO {docnumber} country codes and differing from those in this part of ISO {docnumber} should not be used for an indeterminate period to represent other country names. This provision applies to certain vehicle designations notified under the 1949 and 1968 Conventions on Road Traffic (see Bibliography).
Code elements to which this provision applies should be included in the list of reserved code elements (see 6.5.6) and should not be reallocated during a period of at least fifty years after the date when the countries or organizations concerned have discontinued their use.

==== Exceptional reserved code elements

Code elements may be reserved, in exceptional cases, for country names which the ISO {docnumber}/AG has decided not to include in this part of ISO {docnumber}, but for which an interchange requirement exists. Before such code elements are reserved, advice from the relevant authority must be sought.

==== Reallocation

Before reallocating a former code element or a formerly reserved code element, the ISO {docnumber}/AG shall consult, as appropriate, the authority or agency on whose behalf the code element was reserved, and consideration shall be given to difficulties which might arise from the reallocation.

==== List of reserved code elements

A list of reserved code elements is kept by the ISO {docnumber}/AG secretariat.


=== Advice regarding use of country code elements

The ISO {docnumber}/AG is available for consultation and assistance on the use of country names in coded form.
The ISO {docnumber}/AG does not administer or maintain lists of user-assigned code elements

////
