
[[AnnexA]]
[appendix]
== Registration

=== Registration authority (ISO {docnumber}/RA)

A registration authority (ISO {docnumber}/RA) has been appointed to operate under guidelines provided in this Annex.

It has been entrusted with the following functions with regard to the list of calendar systems and calendar eras, together with code assignments and information associated with each entry:

. to add and eliminate these entries, in accordance with the rules in this document;

. to advise users and ISO member bodies regarding application of such information;

. to update and disseminate such information;

. to maintain a reference list of such information;

. to publish changes made to such information and the history of changes allowing traceability;

. to administer the reservation of the codes.

Changes to the content of the list of entries becomes effective
immediately upon publication.

The criteria provided in <<registration-adding-tzauth>> to <<registration-modify-tz>>
shall be observed by the ISO {docnumber}/RA for changes to the list of
calendar systems and calendar eras, their code assignments and associated information,
and for reservations of code elements.


=== Advisory group (ISO {docnumber}/AG)

An advisory group (ISO {docnumber}/AG) has been appointed to ensure the operations of the registration authority (ISO {docnumber}/RA) are in accordance with guidelines provided in this Annex.


=== Operations on list of calendar systems and calendar eras and their codes

[[registration-adding-tzauth]]
==== Registration of a new calendar system and calendar era

Additions to the list of calendar systems and calendar eras shall be made on the basis of information from upon the request of a member of ISO {docnumber}/AG.

A calendar system is eligible for registration
if it meets the requirements stated in <<scsa-requirements>>.

The proposer is responsible for providing justification to the
ISO {docnumber}/AG regarding the eligibility of such addition.

The ISO {docnumber}/AG will decide upon the addition, on the
basis of eligibility and usage justification.

Code elements will be allocated by the ISO {docnumber}/AG at its
discretion.

Since a calendar system requires at least one calendar era, the application
and assignment of calendar system and calendar era codes can be performed
at once.


////
Additions to the official and international time scale authorities require additional criteria:

* An official time scale authority must be endorsed by a body receiving direct authority by a member of the United Nations.
* An international time scale authority must be endorsed by an international standardization body in liaison with the ISO {docnumber}/AG.
////

==== Modification of a calendar system or calendar era code

Modifications of a code within the list of calendar systems and calendar eras
shall be made upon the request of a member of ISO {docnumber}/AG.

The ISO {docnumber}/AG will decide upon the modification, on the basis of the information received.

The previously assigned code is reserved after modification for
backwards-compatibility purposes.


[[registration-removing-tzauth]]
=== Removal from the list of calendar system and calendar era codes

Removal of a code from the list of calendar systems and calendar eras shall be made upon the request of a member of ISO {docnumber}/AG.

The ISO {docnumber}/AG will decide upon the deletion, on the basis of the information received. The corresponding code element is reserved.



[[registration-deleting-tz]]
=== Removal of elements from the list of calendar system and calendar era codes

Deletion from the list of calendar system and calendar era codes shall be made only by the ISO {docnumber}/AG or upon a request to it.

The ISO {docnumber}/AG will decide upon the deletion, on the basis of the information received. The corresponding code element is reserved.



[[registration-modify-tz]]
=== Alterations to elements on list of calendar system and calendar era codes

Alterations to a registered element shall be made only by the ISO {docnumber}/AG or upon a request to it.

A significant change of name may require the ISO {docnumber}/AG to change the alpha code element concerned. The ISO {docnumber}/AG, however, shall endeavor to maintain stability in the list of code elements.



[[reservation]]
=== Reservation of code elements

==== Introduction

Some code elements are reserved:

* for a limited period when their reservation is the result of
  the deprecation (<<registration-removing-tzauth>>) or the alteration (<<registration-modify-tz>>)
  of an entry;

* for an indeterminate period when the reservation is the result of
  the application of international law or of
  exceptional requests (<<reservation-exceptional>>).

==== Period of non-allocation

Code elements that the ISO {docnumber}/AG has altered or deleted should not be reallocated during a period of at least ten years after the change.

The exact period is determined in each case on the basis of the extent to which the former code element was used.


[[reservation-exceptional]]
==== Exceptional reservations

Code elements may be reserved, in exceptional cases, for calendar systems and calendar eras which the ISO {docnumber}/AG has decided not to include in the lists maintained by ISO {docnumber}/RA, but for which an interchange or encoding requirement exists.

==== Reallocation

Before reallocating a former code element or a formerly reserved code element, the ISO {docnumber}/AG shall consult, as appropriate, the authority or agency on whose behalf the code element was reserved, and consideration shall be given to difficulties which might arise from the reallocation.


==== List of reserved code elements

A list of reserved code elements is kept by the ISO {docnumber}/RA.


=== Advice regarding use of code elements

The ISO {docnumber}/AG is available for consultation and assistance on the use of codes for calendar systems and calendar eras.

