@startuml

'******* CONFIGURATION ************************************************
!include style.uml.inc

class iso15924Code <<dataType>> {
}

class iso639Code <<dataType>> {
}

class LocalizationTag {
  +lang: iso639Code
  +script: iso15924Code
}

class LocalizedString {
  +string: String
  +tag: LocalizationTag
}

@enduml
