@startuml

Calendar system code,English name,Names in other languages,Abbreviation,Specification,Usage populations,Application,Remarks


'******* CONFIGURATION ************************************************
!include style.uml.inc

class Calendar {
  +code: String
  +name: String
  +abbreviation: String[0..*]
  +localizedName: String[0..*]
  +specification: URI[0..*]
  +usagePopulations: String[0..*]
  +usageApplications: String[0..*]
  +notes: String[0..*]
}

'******* CLASS RELATIONS **********************************************


@enduml