@startuml

'******* CONFIGURATION ************************************************
!include style.uml.inc

class Calendar {
  +code: String
  +name: String
  +abbreviation: String[0..*]
  +localizedName: LocalizedString[0..*]
  +specification: URI[0..*]
  +usagePopulations: String[0..*]
  +usageApplications: String[0..*]
  +notes: String[0..*]
}

'******* CLASS RELATIONS **********************************************


@enduml